### ISSUE TITLE
如何引入antd呢

### ISSUE THREAD

**Issue by cuis1** [Lucifier129/react-imvc#47]
使用了两种方式引入antd样式，但是样式都没有成功引入，请问有没有合适的解决方法

1. 本地css文件中加入@import '~antd/dist/antd.css';报错如下
- Error: Did not match any route with path:/~antd/dist/antd.css
    at new ReqError (D:\workPlace\react-imvc-repo\node_modules\_create-app@2.1.0@create-app\lib\share\util.js:20:28)
    at fetchController (D:\workPlace\react-imvc-repo\node_modules\_create-app@2.1.0@create-app\lib\server\createApp.js:115:25)
    at Object.render (D:\workPlace\react-imvc-repo\node_modules\_create-app@2.1.0@create-app\lib\server\createApp.js:68:30)
    at Object.<anonymous> (D:\workPlace\react-imvc-repo\node_modules\_react-imvc@3.0.11@react-imvc\dist\page\createPageRouter.js:228:46)
    at step (D:\workPlace\react-imvc-repo\node_modules\_react-imvc@3.0.11@react-imvc\dist\page\createPageRouter.js:44:23)
    at Object.next (D:\workPlace\react-imvc-repo\node_modules\_react-imvc@3.0.11@react-imvc\dist\page\createPageRouter.js:25:53)
    at D:\workPlace\react-imvc-repo\node_modules\_react-imvc@3.0.11@react-imvc\dist\page\createPageRouter.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (D:\workPlace\react-imvc-repo\node_modules\_react-imvc@3.0.11@react-imvc\dist\page\createPageRouter.js:15:12)
    at D:\workPlace\react-imvc-repo\node_modules\_react-imvc@3.0.11@react-imvc\dist\page\createPageRouter.js:215:56 status: 404 

2. 在imvc.config.ts中配置bable以及webpack

> 依赖版本如下：
    "babel-plugin-import": "^1.13.3",
    "css-loader": "^5.0.1",
    "style-loader": "^2.0.0",
    "less": "^3.12.2",
    "less-loader": "^7.1.0",

>   babel: () => {
    let babelOptions = getBabelConfig();
    babelOptions.plugins.push(['import', { libraryName: 'antd', style: true }]); // 添加 plugins 配置
    return babelOptions;
  }

>   webpack: (webpackConfig) => {
    webpackConfig.module.rules.push(
      {
        //CSS处理
        test: /\.(le|c)ss$/,
        loader: 'style-loader!css-loader!less-loader',
        exclude: /node_modules/,
      },
      {
        //antd样式处理
        test: /\.(le|c)ss$/,
        exclude: /src/,
        use: [
          { loader: 'style-loader' },
          {
            loader: 'css-loader',
          },
          {
            loader: 'less-loader',
            options: { lessOptions: { javascriptEnabled: true } },
          },
        ],
      }
    );
编译时没有报错，但是运行时报错如下

- D:\workPlace\react-imvc-repo\node_modules\_antd@4.8.5@antd\lib\style\index.less:1
@import './themes/index';
^
SyntaxError: Invalid or unexpected token
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.newLoader [as .js] (D:\workPlace\react-imvc-repo\node_modules\_pirates@4.0.1@pirates\lib\index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\workPlace\react-imvc-repo\node_modules\_antd@4.8.5@antd\lib\menu\style\index.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)

**Comment by Lucifier129** [comment]
`react-imvc` 的 `css` 引用方式是通过 `controller` 的 `preload` 配置配合 `Style` 组件完成的，见文档[Style](https://github.com/Lucifier129/react-imvc/blob/master/doc/index.md#style)

```jsx
import React from 'react'
import Controller from 'react-imvc/controller'
import { Style } from 'react-imvc/component' // 加载 Style 组件

export default class extends Controller {
  preload = {
    main: 'path/to/css' // 配置 css 文件路径
  }
  View = View
}

// 当组件渲染时，Style 标签会将 preload 里的同名 css 内容，展示为 style 标签。
function View() {
  return (
    <div>
      <Style name="main" />
    </div>
  )
}
```

将 `antd` 的 `antd.css` 文件拷贝到 `src/css/antd.css`，然后配置 `preload.antd` 为 `/css/antd.css`，让 controller 自动取预加载内容，然后通过 `<Style name="antd" />` 去渲染样式内容。

**Comment by cuis1** [comment]
在/src/css目录中增加private_antd.less文件
@import 'antd/dist/antd.less';


增加gulpfile.js文件
`const gulp = require('gulp');
const less = require('gulp-less');

gulp.task('less', function () {
  return gulp
    .src('./src/**/*.less')
    .pipe(less({ javascriptEnabled: true }))
    .pipe(gulp.dest('./publish/src'))
    .pipe(gulp.dest('./publish/static'))
    .pipe(gulp.dest('./src'));
});

gulp.task('watch', function () {
  return gulp.watch('./src/**/*.less', gulp.series('less'));
});
`
在routes中的Layout文件中插入
`<link href={`${props.publicPath}/css/private_antd.css`} rel="stylesheet" type="text/css"></link>`

package.json中 scripts中增加
    "start": "concurrently 'npm:work' 'npm:watch'",
    "work": "react-imvc start --config imvc.config.js",
    "watch": "gulp watch",

然后就可以愉快的使用less了

**Comment by Lucifier129** [comment]
是的：）

react-imvc 支持通过 preload 方式引入原生 css 文件。编写 less/postcss 可以通过 gulp task 的方式生成原生 css 文件~~
